name: Deploy Fake
on:
  workflow_call:
    inputs:
      ambiente:
        type: string
        required: true

  repository_dispatch:
    types:
      - deploy-remoto
jobs:
    deploy-kubernetes:
       runs-on: ubuntu-latest
       steps:
            - name: Deploy no ambiente
              run: echo "Executando o deloy no ambiente de ${{ inputs.ambiente || github.event.client_payload.ambiente }}"
            - name: Curl Deploy no ambiente
              run: "curl -X POST https://webhook.site/5a51c018-d468-43f7-83c3-a1fd832ac068 -d '{ ambiente: ${{ inputs.ambiente || github.event.client_payload.ambiente }}}'"
